# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'template.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(279, 156)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 81, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(190, 41, 75, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.Canada))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(110, 40, 58, 41))
        self.spinBox.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMinimum(-11)
        self.spinBox.setMaximum(11)
        self.spinBox.setObjectName("spinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 279, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chord Transposition"))
        self.comboBox.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Accord Original</p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "C"))
        self.comboBox.setItemText(1, _translate("MainWindow", "C#/Db"))
        self.comboBox.setItemText(2, _translate("MainWindow", "D"))
        self.comboBox.setItemText(3, _translate("MainWindow", "D#/Eb"))
        self.comboBox.setItemText(4, _translate("MainWindow", "E"))
        self.comboBox.setItemText(5, _translate("MainWindow", "F"))
        self.comboBox.setItemText(6, _translate("MainWindow", "F#/Gb"))
        self.comboBox.setItemText(7, _translate("MainWindow", "G"))
        self.comboBox.setItemText(8, _translate("MainWindow", "G#/Ab"))
        self.comboBox.setItemText(9, _translate("MainWindow", "A"))
        self.comboBox.setItemText(10, _translate("MainWindow", "A#/Bb"))
        self.comboBox.setItemText(11, _translate("MainWindow", "B"))
        self.comboBox_2.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">Accord transposé</p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "C"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "C#/Db"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "D"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "D#/Eb"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "E"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "F"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "F#/Gb"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "G"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "G#/Ab"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "A"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "A#/Bb"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "B"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

